FML:
  vehicle: 
    major_diameter: 18
    minor_diameter: 6

  map:
    path: "maps/map_1677110999.pgm"   # Note map.yaml needs to be in the same location as it will automatically get ingested by the planner 
    cv:
      kernel: [3,3]
      apply: false    # Flag determines whether or not to apply erosion & dilation
      erosion:
        num_iter: 4
      dilation:
        num_iter: 5

    threshold: 254
    inflate: true
    inflation_radius: 8

  planner:
    type: Astar #  out of Choices [ Astar, RRT, PRM, RRTstar] 
    start_point: [288, 95]
    goal_point: [ 30, 22]
    connectivity: "connected-8"      # Could be connected-4 or connected-8
      
  smoothing:
    num_wpts: 500

  output: 
    path: "configs/"